[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "face-emotion"
version = "0.1.0"
description = "Face and Emotion Detection"
requires-python = ">=3.10"
dependencies = [
    "tensorflow",
    "opencv-python",
    "python-dotenv",
    "pandas",
    "numpy",
    "pillow",
    "ultralytics",
    "pyinstaller"
]

[tool.setuptools.packages.find]
where = ["src"]
